name = "Npy"
uuid = "8c784801-6fba-4914-9548-fe67cd7ccd7c"
authors = ["Eric Peng <eric.cypeng@gmail.com>", "Markus Kuhn <Markus.Kuhn@cl.cam.ac.uk>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
